### ISSUE TITLE
Visual Studio 2012 example

### ISSUE THREAD

**Issue by Vamoss** [soyoungshin/ofxGstStandaloneVideo#2]
Hi Soyoung Shin,

can you help to build a Visual Studio 2012 project?
I tried different types of SDKs and configurations, but I didnt had sucess.

Thanks!

**Comment by soyoungshin** [comment]
Hey, I can try, but I won't be able to get to it for another week or two, if at all (I currently have a borrowed Windows box, and I have to ask if I can install visual studio).

There's a lot of info on the ofx thread. http://forum.openframeworks.cc/t/gstreamer-as-a-standalone-addon-for-windows-example/10900

Specifically, you need to install gstreamer per mike creightons instructions: https://github.com/mikecreighton/cinder-GStreamer-Integration

Also, consider reaching out to @outsidecontext who forked this and made some improvements. https://github.com/outsidecontext/ofxGstStandaloneVideo

Try these and let me know where you're at.

Best 
Soyoung

**Comment by soyoungshin** [comment]
Also, this is basically a copy of the built in ofxGstreamerPlayer (or whatever it's named) with changes to be a standalone player. This code has definitely deviated from ofx core so changes will definitely need to be made to make this work. 

I think some people in the forum thread + @outsidecontext have gotten this working. If you comment on there, they will respond back I bet.

Best
Soyoung

**Comment by Vamoss** [comment]
Thanks so much!!!

Worked here :+1:

**Comment by soyoungshin** [comment]
Great. Glad it worked out for you! Post documentation if you've got it.

Best
